<script lang="ts">
  import { getSudoku } from 'sudoku-gen';
  const difficultyLevel = ['easy', 'medium', 'hard', 'expert'];
  let sudoku = $state({});
  let showDebug = $state(false);
  let grid = $state([])
  let solution = $state([])
  let showHighlight = $state(true);
  let showErrors = $state(true);

  function generateBoard(level) {
    sudoku = getSudoku(level);
    grid = makeGrid(sudoku.puzzle);
    solution = makeGrid(sudoku.solution);
  }

  generateBoard('easy');

  let solved = $derived(grid.flat().map(x => x.value).join('') == solution.flat().map(x => x.value).join(''));

  let curRow = $state(0);
  let curCol = $state(0);
  let cellSelected = $derived(grid[curRow][curCol].value);

  const nums = [7,8,9,4,5,6,1,2,3];
  let countAppearances = $derived.by(() => {
    const b = grid.flat().map(x => x.value).filter(x => x != '0');
    const counts = {};
    for (const num of b) {
      counts[num] = counts[num] ? counts[num] + 1 : 1;
    }
    return counts;
  });

  function makeGrid(puzzle) {
    puzzle = puzzle.replaceAll('-', '0');
    let b = [];
    for (let i = 0; i < 9; i++) {
      let row = [];
      for (let j = 0; j < 9; j++) {
        row.push({value:puzzle[i * 9 + j], enabled:puzzle[i * 9 + j] == 0 ? true : false});
      }
      b.push(row);
    }
    return b;
  }

  function handleKeyDown(e) {
    console.log(e.key)
    if (e.key === 'ArrowRight') {
      curCol = (curCol + 1) % 9;
    } else if (e.key === 'ArrowLeft') {
      curCol = (curCol + 8) % 9;
    } else if (e.key === 'ArrowDown') {
      curRow = (curRow + 1) % 9;
    } else if (e.key === 'ArrowUp') {
      curRow = (curRow + 8) % 9;
    }
    if (e.key=='d') {
      showDebug = !showDebug;
    }
    if (e.key === 'Delete') {
      grid[curRow][curCol].value = 0;
    }
    if (e.key >= 1 && e.key <= 9) {
      if(grid[curRow][curCol].enabled) {
        grid[curRow][curCol].value = e.key;
      }
    }

  }

  function handleClick(v,r,c) {
    curRow = r;
    curCol = c;
  }
  function handleNumsClick(value) {
    if(grid[curRow][curCol].enabled) {
      grid[curRow][curCol].value = value;
    }
  }

  function handleButtonClick(level) {
      generateBoard(level);
  }

  function solvePuzzle() {
    console.log('not implemented yet')
  }

</script>

<svelte:body on:keydown={handleKeyDown} />
<main>
  <h1>sudoku</h1>
  <div class="controls">
    {#each difficultyLevel as level}
      <!-- <button class:selectedLevel={level == sudoku.difficulty && !solved} on:click={() => generateBoard(level)}>{level}</button> -->
      <button
        class:selectedLevel={level == sudoku.difficulty && !solved}
        onclick={() => handleButtonClick(level)}
      >{level}</button>
    {/each}
    <!-- <button onclick={solvePuzzle}>solve</button> -->
    <button onclick={() => showHighlight = !showHighlight} class:highlight={showHighlight}>highlight similar</button>
    <button onclick={() => showErrors = !showErrors} class:highlight={showErrors}>toggle show errors</button>
  </div>

  <div class="main-cols">
  
    <div class="board" class:solved={solved}>
      {#each grid as row, r}
        <div class="row">
          {#each row as cell, c}
            <button class="cell"
              onclick={() => handleClick(cell.value,r,c)}
              class:highlight={showHighlight && cellSelected==cell.value && cell.value != 0}
              class:active={r==curRow && c==curCol}
              class:error={showErrors && (solution[r][c].value != cell.value) && (cell.value != 0)}
            >
              <span class="value" class:given={!grid[r][c].enabled} class:hidden={cell.value==0}>{cell.value}</span>
            </button>
          {/each}
        </div>
      {/each}
    </div>

    <div class="nums-wrap">
      {#each nums as value, index}
        <button
          class="num"
          class:done={countAppearances[value] == 9}
          onclick={() => handleNumsClick(value)}>{value}
        </button>
      {/each}
    </div>

  </div>
</main>
<footer>
  <p><a href="https://github.com/tkroo/sudoku-svelte5">source</a></p>
  <p>puzzles generated by <a href="https://github.com/petewritescode/sudoku-gen">sudoku-gen</a></p>
</footer>


{#if showDebug}
<div class="debug">
  countAppearances: {JSON.stringify(countAppearances)}<br>
  curRow: {curRow}, curCol: {curCol}, cellSelected: {cellSelected} solved: {solved}
  <br><br>
  {#each solution.flat() as i, index}
  {i.value}
  {#if (index+1)%3 == 0 && (index+1)%9 != 0}&nbsp;{/if}
  {#if (index+1)%9 == 0}<br>{/if}
  {#if (index+1)%27 == 0}<br>{/if}
  {/each}
  <br><br>
  {JSON.stringify(grid.flat().map(x => parseInt(x.value)))}
  <br><br>
  {JSON.stringify(solution.flat().map(x => parseInt(x.value)))}
</div>
{/if}
